version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://vectorflow.in"
     - aws cloudfront create-invalidation --distribution-id "EA5QDDN47RJLZ" --paths "/*"
 post_build:
   commands:
     - echo "post_build step"
